### PR TITLE
fix(validation): reject additional properties

### PR DESCRIPTION
**Pull request by jzaefferer**

### CODE REVIEW

**Comment by jzaefferer** [comment]
Tested with `make beta`, then:
```
$ ./bundles/1.5.1-beta/sloppy-darwin-amd64 start ../letschat.json
error: failed to parse JSON file ../letschat.json
json: type key is not supported
```
The error message should put more focus on the invalid key; in this case, it looks like "the type _key_ is not supported", which is very misleading.

Better something like `key 'type' not supported`

A "did you mean x?" would be nice, like git has for its commands, but that's certainly out of scope here.

**Comment by jzaefferer** [comment]
The diff looks fine to a hobbyist Go reader like me. I don't like the reflection code, since that seems brittle, but there also doesn't seem to be an alternative.

**Comment by philippfranke** [comment]
As soon as golang/go#15314 gets accepted and merged, we can get rid of the reflection code.

**Comment by jzaefferer** [comment]
Can you add a code comment with the issue reference? 

Otherwise good to land.

**Pull request merged**
