### PR TITLE
Feature/sloppose integration

### PR DESCRIPTION
**Pull request by KevinBusse**
When a docker compose is detected, convert it with sloppose and continue with existing handling.

### CODE REVIEW

**Comment by KevinBusse** [comment]
Sloppose uses an old compose library:
* `github.com/aanand/compose-file/loader` 
* `github.com/aanand/compose-file/types`

Should be replace with:
* `github.com/docker/cli/cli/compose/loader`
* `github.com/docker/cli/cli/compose/types`

**Comment by jzaefferer** [comment]
> Should be replace with:

Should? Or has to be, to make this work? Looking at the build failures, it seems like the latter.

**Comment by jzaefferer** [comment]
Diff looks good. "Just" need to fix `make build`.

**Comment by KevinBusse** [comment]
Yes, it's a hard dependency.

**Comment by jzaefferer** [comment]
I still don't quite understand the problem here. `sloppose` by itself is working, what's the blocker here?

**Comment by jzaefferer** [comment]
Closing this for now. Need to update sloppose to use the same docker libraries that are used in this repo.

**Comment by jzaefferer** [comment]
Let's test this along with https://github.com/sloppyio/sloppose/pull/16

**Pull request merged**
