### PR TITLE
Naive implementation to query credentials from stores

### LINKED ISSUE #12: Extend `docker-login` to check for credentials store
For `sloppy docker-login`, we read `~/.docker/config.json` and upload it to our service, for authenticating private repositories. This usually works fine, but breaks when the file itself doesn't contain the credentials. On OSX, Docker can use the system keychain instead: https://github.com/docker/docker-credential-helpers#usage

Our API already checks for missing auth parameter, and now also checks if there's a credsStore property. It might still be better to catch that issue here (before sending the data anywhere).

For the osxkeychain, we could extend the CLI to get the credentials using the docker-credential-osxkeychain tool. The user is prompted with a keychain dialog in this case. This is how it works:
```
> echo "quay.io" | docker-credential-osxkeychain get
{"ServerURL":"","Username":"mwilz","Secret":"..."}
```

### PR DESCRIPTION
**Pull request by KevinBusse**
To enable credentials from store the code from docker cli is used to request credentials from stores and the resulting config will then be uploaded. This way no changes are required on the server side.

resolves #12

### CODE REVIEW

**Comment by jzaefferer** [comment]
This looks pretty promising!

The failing build looks like its missing a `go get github.com/docker/cli`?

**Comment by KevinBusse** [comment]
Since it's the test that is buggy, I'll have to change the test.

**Comment by jzaefferer** [comment]
Looks like this adds 1.5 MB to the binaries, which is significant, but acceptable. Maybe we can use more of that new package in the future.

Currently I'm testing this with two registries in my `config.json`:
```json
{
	"auths": {
		"https://index.docker.io/v1/": {},
		"registry.k8s-hosting.de": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/17.12.0-ce (darwin)"
	},
	"credsStore": "osxkeychain"
}
```
This ends up failing:
> error: Missing auth parameter for registry.k8s-hosting.de Looks like you're using credsStore=osxkeychain, to which sloppy.io doesn't have access to; try https://admin.sloppy.io/account/credentials instead

With only the `https://index.docker.io/v1/` line it works, so that error seems wrong. There's a call to `c.GetAllCredentials`, so it should work with multiple registries: https://github.com/sloppyio/cli/pull/34/commits/23e45a7236d637f1a80e597250d5b13a092ff51e#diff-47e943ce641d47b23ec5c8e38ce295efR19

 I'm trying to debug this by looking at the request body sent to the backend, but that is currently difficult due to some unrelated issue with my local setup. I don't know the code base well enough to add logging for the request body...

**Comment by KevinBusse** [comment]
Clean up empty auth configs afterwards

**Comment by jzaefferer** [comment]
Nice! Its working well now.

**Pull request merged**
